name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "setting variables"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Print commit id
        run: |
          echo ${{ steps.vars.outputs.sha_short }}
          echo "hello ${{ steps.vars.outputs.sha_short }}"
          echo "'hello ${{ steps.vars.outputs.sha_short }}'"
       
